apiVersion: apps/v1
kind: Deployment
metadata:
  name: testtddtester
  labels:
    app: testtddtester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testtddtester
  template:
    metadata:
      name: testtddtester
      labels:
        app: testtddtester
    spec:
      containers:
        - name: testtddtester
          image: milig/testtddtester:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:tcp://host.minikube.internal/~/test
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always