apiVersion: v1
kind: Service
metadata:
  name: testtddtester
spec:
  selector:
    app: testtddtester
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
  