spring:
  application:
    name:
      - TestTDDTester
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/db.changelog-dev.yaml